[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:indentLine_color_term =239
    let g:indentLine_color_gui = '#708090'
    set list listchars=tab:\¦\ 
'''
[[plugins]]
repo = 'raphamorim/lucario'
hook_add = '''
    colorscheme lucario
    syntax on
    " 256色
    set t_Co=256
    " truecolor
    set termguicolors
    " 背景色
    set background=dark
'''
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    map <C-n> :NERDTreeToggle<CR>
'''

